name: 'install OpenCppCoverage'
description: 'Installs OpenCppCoverage on github actions'
inputs:
  install-folder:
    description: 'The designated install folder'
    required: true
    default: 'C:\Program Files (x86)'
outputs:
  OpenCppCoverage-exe-path:
    description: 'The path to the OpenCppCoverage tool'

runs: 
  using: "composite"
  steps:
    - uses: suisei-cn/actions-download-file@v1
      id: OPEN_CPP_COVERAGE_TAR  # Remember to give an ID if you need the output
      name: Download the file
      with:
        url: "https://github.com/KungFuDonkey/OpenCppCoverageBinaries/releases/download/v0.9.9.0/OpenCppCoverage.tar"
        target: ${{ inputs.install-folder }}
    - name: unzip-OpenCppCoverage
      shell: bash
      run: |
        cd "${{ inputs.install-folder }}"
        tar -xf OpenCppCoverage.tar
        rm OpenCppCoverage.tar
        dir
    - name: check-OpenCppCoverage
      shell: bash
      run: |
        cd "${{ inputs.install-folder }}\OpenCppCoverage"
        dir
        ./OpenCppCoverage.exe
    - name: export-OpenCppCoverage-path
      shell: bash
      env:
        working-directory: ${{ inputs.install-folder }}
        INPUT_FOLDER: ${{ inputs.install-folder }}
      run: |
        EXE_PATH="$INPUT_FOLDER\\OpenCppCoverage\\OpenCppCoverage.exe"
        echo "::set-output name=OpenCppCoverage-exe-path::$EXE_PATH"
        echo "Exe path: $EXE_PATH"
  

