name: 'install OpenCppCoverage'
description: 'Installs OpenCppCoverage on github actions'
inputs:
  install-folder:
    description: 'The designated install folder'
    required: true
    default: 'C:\Program Files (x86)'
outputs:
  OpenCppCoverage-exe-path:
    description: 'The path to the OpenCppCoverage tool'

runs: 
  using: "composite"
  steps:
    - name: install-OpenCppCoverage
      shell: bash
      env:
        working-directory: ${{ inputs.install-folder }}
        INPUT_FOLDER: ${{ inputs.install-folder }}
      run: |
        echo "Install folder = $INPUT_NAME"
        git clone https://github.com/KungFuDonkey/OpenCppCoverageBinaries.git
        EXE_PATH="$INPUT_FOLDER\\OpenCppCoverage\\OpenCppCoverage.exe"
        echo "::set-output name=OpenCppCoverage-exe-path::$EXE_PATH"
        echo "Exe path: $EXE_PATH"
  

