name: 'install OpenCppCoverage'
description: 'Installs OpenCppCoverage on github actions'
inputs:
  install-folder:
    description: 'The designated install folder'
    required: true
    default: 'C:/Program Files (x86)/'
outputs:
  OpenCppCoverage-exe-path:
    description: 'The path to the OpenCppCoverage tool'

runs: 
  using: "composite"
  steps:
    - uses: suisei-cn/actions-download-file@v1
      id: OPEN_CPP_COVERAGE_TAR  # Remember to give an ID if you need the output
      name: Download the file
      with:
        url: "https://github.com/KungFuDonkey/OpenCppCoverageBinaries/releases/download/v0.9.9.0/OpenCppCoverage.tar"
        target: ${{ inputs.install-folder }}

    - name: unzip-OpenCppCoverage
      shell: bash
      run: |
        cd "${{ inputs.install-folder }}"
        tar -xf OpenCppCoverage.tar
        rm OpenCppCoverage.tar

    - name: search-OpenCppCoverage
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "${{inputs.install-folder}}\\OpenCppCoverage\\OpenCppCoverage.exe"
      
    - name: check-OpenCppCoverage-missing
      shell: bash
      if: steps.check_files.outputs.files_exists == 'false'
      run: |
        echo "install of OpenCppCoverage is missing"
        exit -1

    - name: export-OpenCppCoverage-path
      shell: bash
      env:
        INPUT_FOLDER: ${{ inputs.install-folder }}
      run: |
        EXE_PATH="$INPUT_FOLDER\\OpenCppCoverage\\OpenCppCoverage.exe"
        echo "Exe path found: $EXE_PATH"
        echo "::set-output name=OpenCppCoverage-exe-path::$EXE_PATH"
        echo "Setting PATH variable for console usage"
        echo "$INPUT_FOLDER\\OpenCppCoverage" >> $GITHUB_PATH
        echo "Succesfully installed OpenCppCoverage to $INPUT_FOLDER"
      
  

