name: 'install OpenCppCoverage'
description: 'Installs OpenCppCoverage on github actions'
inputs:
  install-folder:
    description: 'The designated install folder'
    required: true
    default: 'C:\Program Files (x86)'
outputs:
  OpenCppCoverage-exe-path:
    description: 'The path to the OpenCppCoverage tool'

runs: 
  using: "composite"
  steps:
    - name: download-OpenCppCoverage
      shell: bash
      env:
        working-directory: ${{ inputs.install-folder }}
      run: |
        cd "${{ inputs.install-folder }}"
        curl -O "${{ inputs.install-folder }}" -L "https://github.com/KungFuDonkey/OpenCppCoverageBinaries/releases/download/v0.9.9.0/OpenCppCoverage.tar"
    - name: unzip-OpenCppCoverage
      shell: bash
      env:
        working-directory: ${{ inputs.install-folder }}
      run: |
        dir
        tar -xf OpenCppCoverage.tar
    - name: check-OpenCppCoverage
      shell: bash
      env: 
        working-directory: ${{ inputs.install-folder }}\OpenCppCoverage
      run: dir
    - name: export-OpenCppCoverage-path
      shell: bash
      env:
        working-directory: ${{ inputs.install-folder }}
        INPUT_FOLDER: ${{ inputs.install-folder }}
      run: |
        EXE_PATH="$INPUT_FOLDER\\OpenCppCoverage\\OpenCppCoverage.exe"
        echo "::set-output name=OpenCppCoverage-exe-path::$EXE_PATH"
        echo "Exe path: $EXE_PATH"
  

